name: rickhumphries
favicon: null
layout_spectrum: 0.50219
typography_spectrum: 0.40628
title: 'thoughts on learning systems, environments and analytics'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.6448895009234548
  rhythmicContrast: 0.11550701828673482
purpose: []
